server:
  port: 3157 #\u9879\u76EE\u542F\u52A8\u8BBF\u95EE\u7AEF\u53E3
spring:
  application:
    name: goods
  datasource: #\u8FDE\u63A5\u6570\u636E\u5E93\u914D\u7F6E
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima-estate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root #\u6570\u636E\u5E93\u7528\u6237
    password: 123456 #\u6570\u636E\u5E93\u5BC6\u7801
  servlet:
    multipart: #\u6587\u4EF6\u4E0A\u4F20\u914D\u7F6E
      max-file-size: 10MB
      max-request-size: 50MB
